name: ff-qt

dependencies:
  - base

executable:
  dependencies:
    - crdt
    - hoppy-runtime
    - qtah #-qt5
    - stm
    - text

    - ff

  ghc-options: -dynamic
  main: Main
  source-dirs: exe
