name: ff-qt
version: '0.2'

dependencies:
  - base

executable:
  dependencies:
    - crdt
    - hoppy-runtime
    - qtah #-qt5
    - stm
    - text

    - ff-core

  ghc-options: -dynamic -optl-pthread
  main: Main
  other-modules:
    - NoteModel
    - Paths_ff_qt
