name: ff
version: '0.2'
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

library:
  dependencies:
    - aeson
    - bytestring
    - crdt
    - directory
    - filepath
    - mainland-pretty
    - mtl
    - optparse-applicative
    - random
    - stm
    - temporary
    - text
    - time
    - typed-process
    - yaml
  source-dirs: lib

executable:
  dependencies:
    - crdt
    - directory
    - filepath
    - mtl
    - mainland-pretty
    - stm
    - terminal-size

    - ff

  main: Main
  other-modules: []
  source-dirs: exe/ff

tests:
  test:
    dependencies:
      - aeson
      - containers
      - crdt
      - crdt-test
      - errors
      - filepath
      - mtl
      - QuickCheck
      - quickcheck-instances
      - tasty-hunit
      - tasty-quickcheck
      - tasty-th
      - text
      - time
      - unordered-containers

      - ff

    main: Main
    source-dirs: test

  features:
    dependencies:
      - blaze-html
      - interpolate
    main: Features.hs

dependencies:
  - base
