resolver: lts-10.7

packages:
  - .
  - ff-qt

extra-deps:
  # ff:
    - crdt-9.3
  # ff:test:
    - git: https://github.com/cblp/crdt.git
      commit: v9.3
      subdirs:
        - crdt-test
  # ff-qt:
    - hoppy-generator-0.4.0
    - hoppy-runtime-0.4.0
    - hoppy-std-0.4.0
    - qtah-cpp-qt5-0.4.0
    - qtah-generator-0.4.0
    - qtah-qt5-0.4.0
    # - git: https://gitlab.com/cblp/qtah.git
    #   commit: 913d45b  # master, 2018-01-13
    #   subdirs:
    #     - qtah
    #     - qtah-cpp
    #     - qtah-generator
    # - ../qtah/qtah
    # - ../qtah/qtah-cpp
    # - ../qtah/qtah-generator

# flags: {qtah: {qt5: true}, qtah-cpp: {qt5: true}}
