resolver: lts-12.10

packages:
  - ff
  - ff-core
  - ff-test
  - ron-storage-fs

  # - ../ron/ron

extra-deps:
  # ff:
  - crdt-10.3
  - git: https://github.com/ff-notes/ron.git
    commit: '4da2335'
    subdirs: [ron]
