resolver: lts-10.4

extra-deps:
  # ff:
    - crdt-6.2

# ff-qt -- temporarily disabled
# extra-deps:
#   - git: https://gitlab.com/cblp/qtah.git
#     commit: 913d45b  # master, 2018-01-13
#     subdirs:
#       - qtah
#       - qtah-cpp
#       - qtah-generator
#   # - ../qtah/qtah
#   # - ../qtah/qtah-cpp
#   # - ../qtah/qtah-generator
# flags: {qtah: {qt5: true}, qtah-cpp: {qt5: true}}
