resolver: lts-12.20

packages:
  - ff
  - ff-core
  - ff-test

extra-deps:
  # ff:
  - crdt-10.3
  # - ron-0.2
  - git: https://github.com/ff-notes/ron.git
    commit: 'dab1c7e'  # 0.2+ EDN Schema
    subdirs: [ron]

  # ron:
  - hedn-0.1.9.1@sha256:01d77f74d211e1187d94e67dd880e3131d0552a5184c7f067b5e686f94b250c7
