resolver: lts-13.30

packages:
  - ff
  - ff-core
  - ff-gtk
  - ff-qt
  - ff-test

extra-deps:
  # binary-instances:
  - binary-orphans-1.0.1
  - time-compat-1.9.2.2

  # ff-core:
  - crdt-10.4
  - github-0.22
  - ron-0.8
  - ron-rdt-0.8
  - ron-schema-0.8
  - ron-storage-0.9

  # ff-gtk:
  - gi-gtk-declarative-0.5.0
  - gi-gtk-declarative-app-simple-0.5.0

  # ff-test:
  - hedgehog-1.0
  - tasty-hedgehog-1.0.0.1

  # gi-gtk-declarative:
  - haskell-gi-0.22.4

  # github:
  - binary-instances-1

  # haskell-gi:
  - gi-cairo-1.0.19
  - gi-gdk-3.0.18
  - gi-gio-2.0.21
  - gi-glib-2.0.19
  - gi-gtk-3.0.28
  - haskell-gi-base-0.22.2

# reduce some deps?
# flags: {comonad: {contravariant: False}}

docker:
  enable: false
  image: ff-ubuntu-16.04

nix:
  packages: [zlib qt5.qtbase gtk3 gobject-introspection]
