resolver: lts-14.10

packages:
  - ff
  - ff-core
  - ff-gtk
  - ff-qtah
  - ff-test

extra-deps:
  # ff-core:
  - crdt-10.4
  - github-0.23
  - ron-0.10
  - ron-rdt-0.10
  # - ron-schema-0.9
  - ron-storage-0.11
  - git: https://github.com/ff-notes/ron.git
    commit: 58eeae5ece8452c2a81e2cd1c111a01a1136fdff  # 0.9 + explicit fields
    subdirs: [ron-schema]
  - shellwords-0.1.2.2

  # ff-gtk:
  - gi-gtk-declarative-0.6.0
  - gi-gtk-declarative-app-simple-0.6.0

  # github:
  - binary-instances-1

  # ff-qtah:
  - hoppy-generator-0.7.0
  - hoppy-runtime-0.7.0
  - hoppy-std-0.7.0
  # - git: https://gitlab.com/khumba/hoppy.git
  #   commit: _
  #   subdirs: [generator, runtime, std]
  # - qtah-cpp-qt5-0.6.0
  # - qtah-generator-0.6.0
  # - qtah-qt5-0.6.0
  - git: https://gitlab.com/cblp/qtah.git
    commit: 4ad4c8194c034c1d949ad16207a8cdabed7848e5  # 0.6.0 + fixes
    subdirs: [qtah, qtah-cpp, qtah-generator]

docker:
  enable: false
  image: ff-ubuntu-16.04

# flags: {qtah-cpp: {qt5: true}}

nix:
  packages: [zlib qt5.qtbase gtk3 gobject-introspection]
