name: ff-upgrade

library:
  dependencies:
    # project
      - ff-core
  source-dirs: lib

executable:
  main: Main

tests:
  json2ron:
    dependencies:
      # global
        - crdt
        - directory
        - filepath
        - process
        - temporary
      # project
        - ff-core
      # package
        - ff-upgrade
    main: TestJson2Ron.hs

dependencies:
  - base
