name: ff-upgrade

library:
  dependencies:
    # project
      - ff-core
  source-dirs: lib

executable:
  main: Main

tests:
  json2ron:
    dependencies:
      # global
        - aeson
        - bytestring
        - interpolate
        - tasty
        - tasty-hunit
      # project
        - ff-test
      # package
        - ff-upgrade
    main: TestJson2Ron.hs

dependencies:
  - base
