name: ff-test

dependencies:
  - base
  - containers

library:
  dependencies:
    # global
    - aeson
    - bytestring
    - crdt
    - lens
    - mtl

    # project
    - ff-core

  exposed-modules:
    - FF.Test

tests:
  test:
    dependencies:
      # global
      - aeson
      - errors
      - github
      - hedgehog
      - interpolate
      - tasty
      - tasty-hedgehog
      - tasty-th
      - text
      - time
      - unordered-containers
      - vector

      # project
      - ff-core

      # package
      - ff-test

    main: Main
    source-dirs: test
